### ISSUE TITLE
Does Hierarchical SIBR load all granularity, nodes and leaves?

### ISSUE THREAD

**Issue by HungNgoCT** [graphdeco-inria/hierarchical-3d-gaussians#101]
Hi.,

Thank you for amazing work and open source.

I understood from the paper, Hierarchical GS just loads granularity for far distance to save memory. However, I understood from the hierarchical SIBR, it loads all granularity, nodes and leaves. Therefore, it should be increase the memory. I think that I missed somewhere, or did not understand somethings.

Could you correct me to understand? Thank you.

a snip of code Hierarchy_loader.cpp file:
        std::vector<half_float::half> half_rotations(allP * 4);
        std::vector<half_float::half> half_scales(allP * 3);
        std::vector<half_float::half> half_opacities(allP);
	std::vector<half_float::half> half_shs(allP * 48);

	infile.read((char*)pos.data(), allP * sizeof(Eigen::Vector3f));
	infile.read((char*)half_rotations.data(), allP * 4 * sizeof(half_float::half));
	infile.read((char*)half_scales.data(), allP * 3 * sizeof(half_float::half));
	infile.read((char*)half_opacities.data(), allP * sizeof(half_float::half));
	infile.read((char*)half_shs.data(), allP * 48 * sizeof(half_float::half));

**Comment by ameuleman** [comment]
Hi, we load the full hierarchies in main memory, but only the relevant portion is sent to the GPU.
