### ISSUE TITLE
I encountered difficulties while installing the viewer

### ISSUE THREAD

**Issue by yjl010228** [graphdeco-inria/hierarchical-3d-gaussians#102]
Respect author! I encountered difficulties while installing the viewer.  When I run `cmake . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_IBR_HIERARCHYVIEWER=ON -DBUILD_IBR_ULR=OFF -DBUILD_IBR_DATASET_TOOLS=OFF -DBUILD_IBR_GAUSSIANVIEWER=OFF`, I get the error:
![image](https://github.com/user-attachments/assets/b3db2df9-473e-4de0-ad86-ea0cad093a74)
And my SIBR_viewers file is:
![image](https://github.com/user-attachments/assets/3384d59b-8735-43a6-8244-0f3662d1ba2d)
Thank you very much!

_Originally posted by @yjl010228 in https://github.com/graphdeco-inria/hierarchical-3d-gaussians/issues/93#issuecomment-2552950950_

**Comment by ameuleman** [comment]
Hi, it seems that the repo was not cloned with `--recursive` (see [setup](https://github.com/graphdeco-inria/hierarchical-3d-gaussians?tab=readme-ov-file#setup)).
