### ISSUE TITLE
Problem with Campus(Calibration) dataset 

### ISSUE THREAD

**Issue by laphisboy** [graphdeco-inria/hierarchical-3d-gaussians#103]
I cannot unzip the campus.zip downloaded from the project page (on ubuntu or mac). 
On my mac I am getting Error79 - Inappropriate file type or format.
Small City dataset unzips fine.
Is there a solution for this unzipping problem with campus.zip?

**Comment by ameuleman** [comment]
Hi, it looks like the archives can only be extracted on Windows. 
Here are archives that should work:
* [Inputs](https://repo-sam.inria.fr/fungraph/hierarchical-3d-gaussians/datasets/full_scenes/campus_linux.zip)
* [Standalone chunk](https://repo-sam.inria.fr/fungraph/hierarchical-3d-gaussians/datasets/standalone_chunks/campus_linux.zip)
* [Results](https://repo-sam.inria.fr/fungraph/hierarchical-3d-gaussians/datasets/results/campus_linux.zip)

**Comment by laphisboy** [comment]
Thank you very very much!
