### ISSUE TITLE
quality and FPS after training

### ISSUE THREAD

**Issue by waynechyr** [graphdeco-inria/hierarchical-3d-gaussians#26]
After I complete the training, how can I check or know the PSNR, LPIPS, SSIM, and FPS information?

**Comment by alanvinx** [comment]
Hi,
you can obtain PSNR, SSIM and LPIPS by running `render_hierarchy.py` after training with the `eval` flag, please follow the detailed instructions here: https://github.com/graphdeco-inria/hierarchical-3d-gaussians?tab=readme-ov-file#large-scenes.

**Comment by waynechyr** [comment]
> Hi, you can obtain PSNR, SSIM and LPIPS by running `render_hierarchy.py` after training with the `eval` flag, please follow the detailed instructions here: https://github.com/graphdeco-inria/hierarchical-3d-gaussians?tab=readme-ov-file#large-scenes.

Thanks for your reply~

**Comment by waynechyr** [comment]
> Hi, you can obtain PSNR, SSIM and LPIPS by running `render_hierarchy.py` after training with the `eval` flag, please follow the detailed instructions here: https://github.com/graphdeco-inria/hierarchical-3d-gaussians?tab=readme-ov-file#large-scenes.


I'm sorry, I might have missed a step, but after successfully running `python scripts/full_train.py --project_dir small_city --extra_training_args "--train_test_exp --eval"`, I am unable to run successfully with `python render_hierarchy.py -s small_city --model_path small_city/output --hierarchy small_city/output/merged.hier  --out_dir small_city/output/renders --eval --scaffold_file small_city/output/scaffold/point_cloud/iteration_30000`. I encounter the following error:

```
Rendering small_city/output
Traceback (most recent call last):
  File "render_hierarchy.py", line 137, in <module>
    scene = Scene(dataset, gaussians, resolution_scales = [1], create_from_hier=True)
  File "/home/wayne/data/hierarchical-3d-gaussians/scene/__init__.py", line 48, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
```

This error seems to be due to a missing file in the small_city datasets.

Additionally, I have a question about this step 

> Ensure that the test.txt is present in all sparse/0/ folders. preprocess/copy_file_to_chunks.py can help copying it to each chunk. Then, the scene can be optimized with eval:

Before executing the training, should we create an empty test.txt file ourselves and then add it to all sparse/0/ folders? I'm not sure if this setup is correct.

Can you please tell me again what the issue is? Thank you!

**Comment by WangHaoran16** [comment]
Hi, #43 can solve this issue.
