### ISSUE TITLE
Potential Bugs

### ISSUE THREAD

**Issue by kevintsq** [graphdeco-inria/hierarchical-3d-gaussians#30]
Images are scaled to [0, 1] when reading:
https://github.com/graphdeco-inria/hierarchical-3d-gaussians/blob/3c601568d3c0557cee3840e4ef79dce3a60ec02b/utils/general_utils.py#L25
But it is divided again in `train _coarse.py`, not `train_post.py` and `train_single.py`:
https://github.com/graphdeco-inria/hierarchical-3d-gaussians/blob/3c601568d3c0557cee3840e4ef79dce3a60ec02b/train_coarse.py#L98-L100
Is this intended?

Besides, should this line be `self.depth_mask = (self.invdepthmap > 0).float()`?
https://github.com/graphdeco-inria/hierarchical-3d-gaussians/blob/3c601568d3c0557cee3840e4ef79dce3a60ec02b/scene/cameras.py#L82

**Comment by alanvinx** [comment]
Hi, thanks for pointing it out. I just pushed a fix for `train_coarse.py`.
