### ISSUE TITLE
Process mistake:IndexError: list index out of range

### ISSUE THREAD

**Issue by SunsMorning** [graphdeco-inria/hierarchical-3d-gaussians#40]
![代码错误](https://github.com/user-attachments/assets/c30214f6-a993-4af0-aeec-cc0d2a281e64)
so how to deal with it? I try all sorts of images.

**Comment by justinyeah** [comment]
I also encountered this issue.

**Comment by SunsMorning** [comment]
I have solved this question, it's structure of folder is like this:
![image](https://github.com/user-attachments/assets/e87cdfc0-7e94-4936-ae98-95e1e0a9410d)
There are seveal image folders in "images", if there is only one folder, it also make mistakes.
