### ISSUE TITLE
How to generate colmap with a single camera dataset？

### ISSUE THREAD

**Issue by Zero2Light** [graphdeco-inria/hierarchical-3d-gaussians#41]
I use a dataset which was captured by  a single camera and when I run the code ‘generate_colmap.py' an error occurs: 

`
making custom matches...
Traceback (most recent call last):
  File "/home/ps/YihangChen/hierarchical-3d-gaussians/preprocess/make_colmap_custom_matcher.py", line 115, in <module>
    add_match(cam_id, matched_cam_id, current_image_file, matched_frame_id)
  File "/home/ps/YihangChen/hierarchical-3d-gaussians/preprocess/make_colmap_custom_matcher.py", line 102, in add_match
    matches_str.append(f"{cam_folder_list[cam_id]}/{current_image_file} {cam_folder_list[cam_id + matched_cam_id]}/{matched_image_file}\n")
                          ~~~~~~~~~~~~~~~^^^^^^^^
IndexError: list index out of range
Error executing make_colmap_custom_matcher: Command
`

Is there a version of code for a single camera to generate colmap?

**Comment by VerseWei** [comment]
I am encountering thee same probleem, could you share your method? Thanks!

**Comment by Zero2Light** [comment]
See this，https://github.com/graphdeco-inria/hierarchical-3d-gaussians/issues/3
