### ISSUE TITLE
Ellipsoid in SIBR Viewer

### ISSUE THREAD

**Issue by Gaaaavin** [graphdeco-inria/hierarchical-3d-gaussians#45]
I noticed that the SIBR viewer has no option to visualize ellipsoid like those provided for 3DGS.
This is very important for debugging and parameter tuning. How can I modify the code to enbale this function?

**Comment by Snosixtyboo** [comment]
Hi,

unfortunately, we don't have a renderer right now that can do ellipsoid rendering at this scale. But it should still be possible to load the individual chunk .ply files into the old (3DGS) viewer and take a look at the ellipsoids there!

**Comment by Gaaaavin** [comment]
Thank you for the information!
