### ISSUE TITLE
Loading ply from trained_chunks folder in SIBR_gaussianViewer_app viewer shows different result

### ISSUE THREAD

**Issue by anchun** [graphdeco-inria/hierarchical-3d-gaussians#47]
Thank you for your great work for hierarchical 3DGS!
After training with wayve dataset, the result shows great as follows:
![h3dgs-good](https://github.com/user-attachments/assets/469db119-270f-4679-a64e-cab014d55d40)

When I look into the traing_chunk  in details, it shows there are some intermidiate point_cloud result in output/trained_chunks/0_0. when I tried to load it in original [3DGS viewer](https://github.com/graphdeco-inria/gaussian-splatting?tab=readme-ov-file#navigation-in-sibr-viewers), but it shows some artifacts(e.g. some white lines near the wheel). 
![sibr_3dgs](https://github.com/user-attachments/assets/85314df2-0a63-46c4-86d2-a61b437cf0a4)
The loading command is: SIBR_gaussianViewer_app -m ./output/trained_chunks/0_0. it seems the opacity is not translated well in the original 3DGS viewer.
So My question is: what's the main difference between the original ply format and the new ply format in hierarchical-3d-gaussians? Thanks!

**Comment by Snosixtyboo** [comment]
Hi,

thanks for trying! Yes, there is a key difference: the new viewer uses correct antialiasing. This is something that will be backported to the original 3DGS viewer soon as well, so you should be able to view them correctly.

Hth!
Bernhard

**Comment by anchun** [comment]
> Hi,
> 
> thanks for trying! Yes, there is a key difference: the new viewer uses correct antialiasing. This is something that will be backported to the original 3DGS viewer soon as well, so you should be able to view them correctly.
> 
> Hth! Bernhard

Thank you, Bernhard! it's related to DGR_FIX_AA settings in the code.

Anchun

**Comment by timi-liuliang** [comment]
@anchun Hello, may I ask where did you obtain the Wayve data? What processing steps were taken to make the Wayve data usable for training with hierarchical 3D Gaussians ([WayveScenes 101](https://drive.google.com/drive/u/0/folders/1XXlhGut7c5PVeBj4qwORlHoGdeSYxGgt)  uses the Fisheye model)?
