### ISSUE TITLE
SIBR view problem

### ISSUE THREAD

**Issue by Zero2Light** [graphdeco-inria/hierarchical-3d-gaussians#74]
`MESA_GL_VERSION_OVERRIDE=4.5 SIBR_viewers/install/bin/SIBR_gaussianHierarchyViewer_app --path ${DATASET_DIR}/camera_calibration/aligned --scaffold ${DATASET_DIR}/output/scaffold/point_cloud/iteration_30000 --model-path ${DATASET_DIR}/output/merged.hier --images-path ${DATASET_DIR}/camera_calibration/rectified/images --budget 7000
[SIBR] --  INFOS  --:   Initialization of GLFW
WARNING: dzn is not a conformant Vulkan implementation, testing use only.
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Microsoft Direct3D12 (NVIDIA GeForce RTX 4070 SUPER)) doesn't support base Zink requirements: feats.features.logicOp have_EXT_custom_border_color have_EXT_line_rasterization
[SIBR] --  INFOS  --:   OpenGL Version: 4.5 (Compatibility Profile) Mesa 24.2.1 - kisak-mesa PPA[major: 4, minor: 5]
[SIBR] ##  ERROR  ##:   FILE /home/zero/SJTU_3DGS/hierarchical-3d-gaussians/SIBR_viewers/src/core/scene/ParseData.cpp
                        LINE 560, FUNC getParsedData
                        Cannot determine type of dataset at /.../camera_calibration/aligned
terminate called after throwing an instance of 'std::runtime_error'
  what():  See log for message errors
Aborted`

I use a WSL2 ubuntu22.04 to view the trained large sence ply file, which was captured by only one camera and without masks. When I use SIBR viewer to open it, it says "Cannot determine type of dataset".
 Is there any way I can fix the problem?

**Comment by ameuleman** [comment]
Hi,
Does `${DATASET_DIR}/camera_calibration/aligned` contain the calibration files?

**Comment by Zero2Light** [comment]
Yes, thanks for your reply!
I've solved this problem, I had this problem when I was using WSL2 before, and it was able to display correctly after installing Ubuntu dual system later.
There may be some possible communication issue with cuda when using SIBR_viewer in WSL2.
