### ISSUE TITLE
Why the background color of SmallCity is not set to white?

### ISSUE THREAD

**Issue by Vilour** [graphdeco-inria/hierarchical-3d-gaussians#8]
Since it's outdoor and during the day, would it be better if the background color is white?

**Comment by White-Mask-230** [comment]
It has logic, but to solve the problem, we need more information about your PC, the version of this project, and the version of the librarys

**Comment by ameuleman** [comment]
Hi,
We use a random background during the optimisation. This makes some surfaces more opaque, which can help when rendering a novel view away from the inputs

**Comment by HungNgoCT** [comment]
> Hi, We use a random background during the optimisation. This makes some surfaces more opaque, which can help when rendering a novel view away from the inputs. The sky will be handled by the skybox optimized in the coarse stage

Hi @ameuleman ,

I saw that the default setting in the coarse stage for iterations is just 30k steps. If the number of images is large, say 10k, is 30k steps of training as default setting sufficient to optimize? The question I would like to ask here is whether it is better if number of training steps increase?
