### ISSUE TITLE
The difference between render and train in Table 5

### ISSUE THREAD

**Issue by smart4654154** [graphdeco-inria/hierarchical-3d-gaussians#81]
![image](https://github.com/user-attachments/assets/d1a6385c-86fa-4243-8ed7-54f187b12e6a)
your work is good
The difference between render and train in Table 5?
I think #render is the number of 3DGS required to render an image
I think #train is the additional number of 3DGS required to render the next image
![image](https://github.com/user-attachments/assets/abdf3685-22ca-4297-8b6d-e3e62c8f7569)
thankthank you

**Comment by ameuleman** [comment]
Hi, yes, #render is the average number of Gaussians required on the GPU to render and #trans is the average number of Gaussians transferred per image.
