### ISSUE TITLE
question about the number of gaussians in .ply and .hier

### ISSUE THREAD

**Issue by Yang-Xijie** [graphdeco-inria/hierarchical-3d-gaussians#88]
I followed the procedure described in https://github.com/graphdeco-inria/hierarchical-3d-gaussians?tab=readme-ov-file#single-chunk to get the following model files of the standalone chunk for small_city:

- output/
    - hierarchy.hier
    - hierarchy.hier_opt
    - point_cloud/
        - iteration_30000/
            - point_cloud.ply

I found that `point_cloud.ply` has 4933595 gaussians, and both `hierarchy.hier` and `hierarchy.hier_opt` have 7028173 nodes (gaussians) (+42.5%).

I know that gaussians in .ply file are the leaves in .hier files (as described in paper Sec. 4.1). However, in this case, number of nodes in .hier files should be twice of that in `point_cloud.ply`. Why is the number of gaussians increased by 42.5% instead of 100%?

**Comment by ameuleman** [comment]
Hi,
The increase in size you observe is expected. After building the initial hierarchy, a compacting step removes intermediate nodes if they are only marginally bigger than their children (Sec. 5.2).
