### ISSUE TITLE
How To Get The Evaluation On My Own Dataset

### ISSUE THREAD

**Issue by Eleven-11-yuzheng** [graphdeco-inria/hierarchical-3d-gaussians#97]
How can I generate the evaluations?
I use my own dataset to make chunks, and i have my own test.txt under one of the son chunks(which i want to get the evaluation)
But when i start single_train, the terminal will display "test images： ; train images: xxx"
I‘m confused about the test images? It seems that the "test.txt" isn't useful
My progress:
①generate_colmap
②generate_chunks
③generate_depth
④make the test.txt and put it under the myChunk/sprase/0
⑤single_train myChunk
⑥the test.txt did not use

And I've tried your example small_city, it's OK
I want to know how can i do the evaluation on my own dataset
![image](https://github.com/user-attachments/assets/7f729e19-2258-4852-8f88-3fb41aae1634)

**Comment by Eleven-11-yuzheng** [comment]
I really want to use your small_city dataset, but out of memory (single_train) makes me unhappy
Hope you can answer my question
Thank you so much!!!!

**Comment by Ruidong6688** [comment]
哈喽，我想问一下test.txt里的内容需要是怎么样格式的，谢谢！
